#include <string>
#include <vector>
#include <cstdint>
#include <unordered_map>

#ifndef DNS_RR_HPP // DNS_RR_HPP
#define DNS_RR_HPP


namespace dns {
    // list per IANA DNS Parameters - DNS CLASSes (https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#dns-parameters-2)
    enum rr_class_enum : uint16_t {
        RR_CLASS_IN = 1,
        RR_CLASS_CH = 3,
        RR_CLASS_HS = 4,
        RR_CLASS_NONE = 254,
        RR_CLASS_ANY = 255
    };

    typedef enum rr_class_enum rr_class_t;

    // list per IANA DNS Parameters - RR TYPEs (https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#dns-parameters-4)
    enum rr_type_enum : uint16_t {
        // 0 is reserved
        RR_TYPE_A = 1,
        RR_TYPE_NS = 2,
        RR_TYPE_MD = 3,
        RR_TYPE_MF = 4,
        RR_TYPE_CNAME = 5,
        RR_TYPE_SOA = 6,
        RR_TYPE_MB = 7,
        RR_TYPE_MG = 8,
        RR_TYPE_MR = 9,
        RR_TYPE_NULL = 10,
        RR_TYPE_WKS = 11,
        RR_TYPE_PTR = 12,
        RR_TYPE_HINFO = 13,
        RR_TYPE_MINFO = 14,
        RR_TYPE_MX = 15,
        RR_TYPE_TXT = 16,
        RR_TYPE_RP = 17,
        RR_TYPE_AFSDB = 18,
        RR_TYPE_X25 = 19,
        RR_TYPE_ISDN = 20,
        RR_TYPE_RT = 21,
        RR_TYPE_NSAP = 22,
        RR_TYPE_NSAP_PTR = 23,
        RR_TYPE_SIG = 24,
        RR_TYPE_KEY = 25,
        RR_TYPE_PX = 26,
        RR_TYPE_GPOS = 27,
        RR_TYPE_AAAA = 28,
        RR_TYPE_LOC = 29,
        RR_TYPE_NXT = 30,
        RR_TYPE_EID = 31,
        RR_TYPE_NIMLOC = 32,
        RR_TYPE_SRV = 33,
        RR_TYPE_ATMA = 34,
        RR_TYPE_NAPTR = 35,
        RR_TYPE_KX = 36,
        RR_TYPE_CERT = 37,
        RR_TYPE_A6 = 38,
        RR_TYPE_DNAME = 39,
        RR_TYPE_SINK = 40,
        RR_TYPE_OPT = 41,
        RR_TYPE_APL = 42,
        RR_TYPE_DS = 43,
        RR_TYPE_SSHFP = 44,
        RR_TYPE_IPSECKEY = 45,
        RR_TYPE_RRSIG = 46,
        RR_TYPE_NSEC = 47,
        RR_TYPE_DNSKEY = 48,
        RR_TYPE_DHCID = 49,
        RR_TYPE_NSEC3 = 50,
        RR_TYPE_NSEC3PARAM = 51,
        RR_TYPE_TLSA = 52,
        RR_TYPE_SMIMEA = 53,
        // 54 is unassigned
        RR_TYPE_HIP = 55,
        RR_TYPE_NINFO = 56,
        RR_TYPE_RKEY = 57,
        RR_TYPE_TALINK = 58,
        RR_TYPE_CDS = 59,
        RR_TYPE_CDNSKEY = 60,
        RR_TYPE_OPENPGPKEY = 61,
        RR_TYPE_CSYNC = 62,
        RR_TYPE_ZONEMD = 63,
        RR_TYPE_SVCB = 64,
        RR_TYPE_HTTPS = 65,
        RR_TYPE_DSYNC = 66,
        RR_TYPE_HHIT = 67,
        RR_TYPE_BRID = 68,
        // 69-98 are unassigned
        RR_TYPE_SPF = 99,
        RR_TYPE_UINFO = 100,
        RR_TYPE_UID = 101,
        RR_TYPE_GID = 102,
        RR_TYPE_UNSPEC = 103,
        RR_TYPE_NID = 104,
        RR_TYPE_L32 = 105,
        RR_TYPE_L64 = 106,
        RR_TYPE_LP = 107,
        RR_TYPE_EUI48 = 108,
        RR_TYPE_EUI64 = 109,
        // 110-127 are unassigned
        RR_TYPE_NXNAME = 128,
        // 129-248 are unassigned
        RR_TYPE_TKEY = 249,
        RR_TYPE_TSIG = 250,
        RR_TYPE_IFXR = 251,
        RR_TYPE_AXFR = 252,
        RR_TYPE_MAILB = 253,
        RR_TYPE_MAILA = 254,
        RR_TYPE_ANY = 255,
        RR_TYPE_URI = 256,
        RR_TYPE_CAA = 257,
        RR_TYPE_AVC = 258,
        RR_TYPE_DOA = 259,
        RR_TYPE_AMTRELAY = 260,
        RR_TYPE_RESINFO = 261,
        RR_TYPE_WALLET = 262,
        RR_TYPE_CLA = 263,
        RR_TYPE_IPN = 264,
        // 265-32767 are unassigned
        RR_TYPE_TA = 32768,
        RR_TYPE_DLV = 32769
    };

    typedef enum rr_type_enum rr_type_t;

    static std::unordered_map<std::string, rr_type_t> str_to_rr_type_t = {
        {"A", RR_TYPE_A},
        {"NS", RR_TYPE_NS},
        {"MD", RR_TYPE_MD},
        {"MF", RR_TYPE_MF},
        {"CNAME", RR_TYPE_CNAME},
        {"SOA", RR_TYPE_SOA},
        {"MB", RR_TYPE_MB},
        {"MG", RR_TYPE_MG},
        {"MR", RR_TYPE_MR},
        {"NULL", RR_TYPE_NULL},
        {"WKS", RR_TYPE_WKS},
        {"PTR", RR_TYPE_PTR},
        {"HINFO", RR_TYPE_HINFO},
        {"MINFO", RR_TYPE_MINFO},
        {"MX", RR_TYPE_MX},
        {"TXT", RR_TYPE_TXT},
        {"RP", RR_TYPE_RP},
        {"AFSDB", RR_TYPE_AFSDB},
        {"X25", RR_TYPE_X25},
        {"ISDN", RR_TYPE_ISDN},
        {"RT", RR_TYPE_RT},
        {"NSAP", RR_TYPE_NSAP},
        {"NSAP-PTR", RR_TYPE_NSAP_PTR},
        {"SIG", RR_TYPE_SIG},
        {"KEY", RR_TYPE_KEY},
        {"PX", RR_TYPE_PX},
        {"GPOS", RR_TYPE_GPOS},
        {"AAAA", RR_TYPE_AAAA},
        {"LOC", RR_TYPE_LOC},
        {"NXT", RR_TYPE_NXT},
        {"EID", RR_TYPE_EID},
        {"NIMLOC", RR_TYPE_NIMLOC},
        {"SRV", RR_TYPE_SRV},
        {"ATMA", RR_TYPE_ATMA},
        {"NAPTR", RR_TYPE_NAPTR},
        {"KX", RR_TYPE_KX},
        {"CERT", RR_TYPE_CERT},
        {"A6", RR_TYPE_A6},
        {"DNAME", RR_TYPE_DNAME},
        {"SINK", RR_TYPE_SINK},
        {"OPT", RR_TYPE_OPT},
        {"APL", RR_TYPE_APL},
        {"DS", RR_TYPE_DS},
        {"SSHFP", RR_TYPE_SSHFP},
        {"IPSECKEY", RR_TYPE_IPSECKEY},
        {"RRSIG", RR_TYPE_RRSIG},
        {"NSEC", RR_TYPE_NSEC},
        {"DNSKEY", RR_TYPE_DNSKEY},
        {"DHCID", RR_TYPE_DHCID},
        {"NSEC3", RR_TYPE_NSEC3},
        {"NSEC3PARAM", RR_TYPE_NSEC3PARAM},
        {"TLSA", RR_TYPE_TLSA},
        {"SMIMEA", RR_TYPE_SMIMEA},
        {"HIP", RR_TYPE_HIP},
        {"NINFO", RR_TYPE_NINFO},
        {"RKEY", RR_TYPE_RKEY},
        {"TALINK", RR_TYPE_TALINK},
        {"CDS", RR_TYPE_CDS},
        {"CDNSKEY", RR_TYPE_CDNSKEY},
        {"OPENPGPKEY", RR_TYPE_OPENPGPKEY},
        {"CSYNC", RR_TYPE_CSYNC},
        {"ZONEMD", RR_TYPE_ZONEMD},
        {"SVCB", RR_TYPE_SVCB},
        {"HTTPS", RR_TYPE_HTTPS},
        {"DSYNC", RR_TYPE_DSYNC},
        {"HHIT", RR_TYPE_HHIT},
        {"BRID", RR_TYPE_BRID},
        {"SPF", RR_TYPE_SPF},
        {"UINFO", RR_TYPE_UINFO},
        {"UID", RR_TYPE_UID},
        {"GID", RR_TYPE_GID},
        {"UNSPEC", RR_TYPE_UNSPEC},
        {"NID", RR_TYPE_NID},
        {"L32", RR_TYPE_L32},
        {"L64", RR_TYPE_L64},
        {"LP", RR_TYPE_LP},
        {"EUI48", RR_TYPE_EUI48},
        {"EUI64", RR_TYPE_EUI64},
        {"NXNAME", RR_TYPE_NXNAME},
        {"TKEY", RR_TYPE_TKEY},
        {"TSIG", RR_TYPE_TSIG},
        {"IFXR", RR_TYPE_IFXR},
        {"AXFR", RR_TYPE_AXFR},
        {"MAILB", RR_TYPE_MAILB},
        {"MAILA", RR_TYPE_MAILA},
        {"ANY", RR_TYPE_ANY},
        {"URI", RR_TYPE_URI},
        {"CAA", RR_TYPE_CAA},
        {"AVC", RR_TYPE_AVC},
        {"DOA", RR_TYPE_DOA},
        {"AMTRELAY", RR_TYPE_AMTRELAY},
        {"RESINFO", RR_TYPE_RESINFO},
        {"WALLET", RR_TYPE_WALLET},
        {"CLA", RR_TYPE_CLA},
        {"IPN", RR_TYPE_IPN},
        {"TA", RR_TYPE_TA},
        {"DLV", RR_TYPE_DLV}
    };
    
    static std::unordered_map<rr_type_t, std::string> rr_type_t_to_str = {
        {RR_TYPE_A, "A"},
        {RR_TYPE_NS, "NS"},
        {RR_TYPE_MD, "MD"},
        {RR_TYPE_MF, "MF"},
        {RR_TYPE_CNAME, "CNAME"},
        {RR_TYPE_SOA, "SOA"},
        {RR_TYPE_MB, "MB"},
        {RR_TYPE_MG, "MG"},
        {RR_TYPE_MR, "MR"},
        {RR_TYPE_NULL, "NULL"},
        {RR_TYPE_WKS, "WKS"},
        {RR_TYPE_PTR, "PTR"},
        {RR_TYPE_HINFO, "HINFO"},
        {RR_TYPE_MINFO, "MINFO"},
        {RR_TYPE_MX, "MX"},
        {RR_TYPE_TXT, "TXT"},
        {RR_TYPE_RP, "RP"},
        {RR_TYPE_AFSDB, "AFSDB"},
        {RR_TYPE_X25, "X25"},
        {RR_TYPE_ISDN, "ISDN"},
        {RR_TYPE_RT, "RT"},
        {RR_TYPE_NSAP, "NSAP"},
        {RR_TYPE_NSAP_PTR, "NSAP-PTR"},
        {RR_TYPE_SIG, "SIG"},
        {RR_TYPE_KEY, "KEY"},
        {RR_TYPE_PX, "PX"},
        {RR_TYPE_GPOS, "GPOS"},
        {RR_TYPE_AAAA, "AAAA"},
        {RR_TYPE_LOC, "LOC"},
        {RR_TYPE_NXT, "NXT"},
        {RR_TYPE_EID, "EID"},
        {RR_TYPE_NIMLOC, "NIMLOC"},
        {RR_TYPE_SRV, "SRV"},
        {RR_TYPE_ATMA, "ATMA"},
        {RR_TYPE_NAPTR, "NAPTR"},
        {RR_TYPE_KX, "KX"},
        {RR_TYPE_CERT, "CERT"},
        {RR_TYPE_A6, "A6"},
        {RR_TYPE_DNAME, "DNAME"},
        {RR_TYPE_SINK, "SINK"},
        {RR_TYPE_OPT, "OPT"},
        {RR_TYPE_APL, "APL"},
        {RR_TYPE_DS, "DS"},
        {RR_TYPE_SSHFP, "SSHFP"},
        {RR_TYPE_IPSECKEY, "IPSECKEY"},
        {RR_TYPE_RRSIG, "RRSIG"},
        {RR_TYPE_NSEC, "NSEC"},
        {RR_TYPE_DNSKEY, "DNSKEY"},
        {RR_TYPE_DHCID, "DHCID"},
        {RR_TYPE_NSEC3, "NSEC3"},
        {RR_TYPE_NSEC3PARAM, "NSEC3PARAM"},
        {RR_TYPE_TLSA, "TLSA"},
        {RR_TYPE_SMIMEA, "SMIMEA"},
        {RR_TYPE_HIP, "HIP"},
        {RR_TYPE_NINFO, "NINFO"},
        {RR_TYPE_RKEY, "RKEY"},
        {RR_TYPE_TALINK, "TALINK"},
        {RR_TYPE_CDS, "CDS"},
        {RR_TYPE_CDNSKEY, "CDNSKEY"},
        {RR_TYPE_OPENPGPKEY, "OPENPGPKEY"},
        {RR_TYPE_CSYNC, "CSYNC"},
        {RR_TYPE_ZONEMD, "ZONEMD"},
        {RR_TYPE_SVCB, "SVCB"},
        {RR_TYPE_HTTPS, "HTTPS"},
        {RR_TYPE_DSYNC, "DSYNC"},
        {RR_TYPE_HHIT, "HHIT"},
        {RR_TYPE_BRID, "BRID"},
        {RR_TYPE_SPF, "SPF"},
        {RR_TYPE_UINFO, "UINFO"},
        {RR_TYPE_UID, "UID"},
        {RR_TYPE_GID, "GID"},
        {RR_TYPE_UNSPEC, "UNSPEC"},
        {RR_TYPE_NID, "NID"},
        {RR_TYPE_L32, "L32"},
        {RR_TYPE_L64, "L64"},
        {RR_TYPE_LP, "LP"},
        {RR_TYPE_EUI48, "EUI48"},
        {RR_TYPE_EUI64, "EUI64"},
        {RR_TYPE_NXNAME, "NXNAME"},
        {RR_TYPE_TKEY, "TKEY"},
        {RR_TYPE_TSIG, "TSIG"},
        {RR_TYPE_IFXR, "IFXR"},
        {RR_TYPE_AXFR, "AXFR"},
        {RR_TYPE_MAILB, "MAILB"},
        {RR_TYPE_MAILA, "MAILA"},
        {RR_TYPE_ANY, "ANY"},
        {RR_TYPE_URI, "URI"},
        {RR_TYPE_CAA, "CAA"},
        {RR_TYPE_AVC, "AVC"},
        {RR_TYPE_DOA, "DOA"},
        {RR_TYPE_AMTRELAY, "AMTRELAY"},
        {RR_TYPE_RESINFO, "RESINFO"},
        {RR_TYPE_WALLET, "WALLET"},
        {RR_TYPE_CLA, "CLA"},
        {RR_TYPE_IPN, "IPN"},
        {RR_TYPE_TA, "TA"},
        {RR_TYPE_DLV, "DLV"}
    };

    static std::unordered_map<std::string, rr_class_t> str_to_rr_class_t = {
        {"IN", RR_CLASS_IN},
        {"CH", RR_CLASS_CH},
        {"HS", RR_CLASS_HS},
        {"NONE", RR_CLASS_NONE},
        {"ANY", RR_CLASS_ANY}
    };

    static std::unordered_map<rr_class_t, std::string> rr_class_t_to_str = {
        {RR_CLASS_IN, "IN"},
        {RR_CLASS_CH, "CH"},
        {RR_CLASS_HS, "HS"},
        {RR_CLASS_NONE, "NONE"},
        {RR_CLASS_ANY, "ANY"}
    };
    
    // Forward declarations for operator<< overloads
    std::ostream& operator<<(std::ostream& os, const rr_class_t& rclass);
    std::ostream& operator<<(std::ostream& os, const rr_type_t& rtype);
    
    class DNSResourceRecord {
    public:
        std::string name;
        rr_type_t type;
        rr_class_t rclass = RR_CLASS_IN; // IN
        uint32_t ttl;
        std::vector<uint8_t> rdata;
        std::vector<uint8_t> toWire() const;
        friend std::ostream& operator<<(std::ostream& os, const DNSResourceRecord& rr);
    };
}
#endif // DNS_RR_HPP
